### ISSUE TITLE
Error: "Message" is required to verify the SNS Message

### ISSUE THREAD

**Issue by i-ira** [aws/aws-php-sns-message-validator#39]
Same error of that mentioned in #29, this issue has plagued me as well, in particular when sending SNS Notifications via Elastic Transcoder. Elastic Transcoder Notification payloads don't seem to contain a "Message" field. Is there any work around's to this?

Here is an example of an Elastic Transcoder Notification, recieved via E-Mail:

```
{
  "state" : "COMPLETED",
  "version" : "2012-09-25",
  "jobId" : "1559924750698-dejdio",
  "pipelineId" : "1559968916611-abcdef",
  "input" : {
    "key" : "MySong.mp3",
    "container" : "auto"
  },
  "inputCount" : 1,
  "outputs" : [ {
    "id" : "1",
    "presetId" : "1351620000001-100110",
    "key" : "MySong.m4a",
    "thumbnailPattern" : "",
    "rotate" : "auto",
    "status" : "Complete",
    "duration" : 157
  } ]
}
```

**Comment by hamid09430** [comment]
@i-ira 
Try This Way....

$msgBody = file_get_contents('php://input');
        $response = json_decode($msgBody, True);
        if (isset($response['Type']) && $response['Type'] === 'SubscriptionConfirmation') {
            file_get_contents($response['SubscribeURL']);
            logger("Amazon SNS Subscription Confirmed: Subscription URL: " . $response['SubscribeURL']);
            die;
        }
        $video_id = $response['detail']['userMetadata']['video_id'];

**Comment by i-ira** [comment]
well obviously I can go the route of manually retrieving the data myself but that defeats the purpose of using the package which has additional security provisions as well. This should be fixed within the scope of the package.

**Comment by motia** [comment]
@i-ira , You probably enabled the `raw message delivery` option on your SNS subscription. And you should disable it to use this package.

The package can not execute any security checks on payloads received with this option, because the data necessary for security checks is missing. So, I think the package is designed to not work with payloads such you receive.

**Comment by i-ira** [comment]
> @i-ira , You probably enabled the `raw message delivery` option on your SNS subscription. And you should disable it to use this package.
> 
> The package can not execute any security checks on payloads received with this option, because the data necessary for security checks is missing. So, I think the package is designed to not work with payloads such you receive.

Thanks @motia that was precisely the issue. Having `raw message delivery` enabled changed the structure of the SNS message payload. 

rather than use the `Message::fromRawPostData()` func, I had to use the `Message::fromPsrRequest(RequestInterface $request)` func. To use that function however you need to install a few laravel packages to interpret typical Laravel requests to PSR-7 compatible, [as outlined in the Doc's](https://laravel.com/docs/5.1/requests#psr7-requests). Hope this helps anyone in the future, cheers!

**Comment by diehlaws** [comment]
Apologies for the lack of response on this from our end @i-ira. I'm glad to hear the suggestion provided by @motia worked as expected for you. I'll be closing out this issue since it looks like things are in order here, however if you have additional questions for us or require further guidance on this please don't hesitate to leave a comment and we'll re-open the issue to continue working on it.
